<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Solo aplicar si estamos conectados a PostgreSQL (no aplica en entorno local con MySQL)
        if (DB::getDriverName() === 'pgsql') {
            $tables = [
                'usuarios' => 'id_usuario',
                'productos' => 'id_producto',
                'categorias' => 'id_categoria',
                'clientes' => 'id_cliente',
                'ventas' => 'id_venta',
                'detalle_venta' => 'id_detalle',
                'movimientos_inventario' => 'id_movimiento',
            ];

            foreach ($tables as $table => $column) {
                try {
                    // Alterar columna de identidad a GENERATED BY DEFAULT para permitir insertar IDs explícitos
                    DB::statement("ALTER TABLE {$table} ALTER COLUMN {$column} SET GENERATED BY DEFAULT;");
                } catch (\Throwable $e) {
                    // Ignorar errores si la tabla o columna no existen en el esquema actual
                }
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // No revertir, ya que GENERATED BY DEFAULT es compatible con el comportamiento por defecto
    }
};
